Repository AY2425S2-CS2103T-F10-2/tp, pull requests merged in 2025-03, with the labels that each got.

#50 Prevent Duplicate Households, ID Formatting, and Help Guide Updates
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/commands/AddHouseholdCommand.java
  src/main/java/seedu/address/logic/commands/AddSessionCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteHouseholdCommand.java
  src/main/java/seedu/address/logic/commands/EditHouseholdCommand.java
  src/main/java/seedu/address/logic/commands/FindHouseholdCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/ListHouseholdsCommand.java
  src/main/java/seedu/address/logic/commands/ViewHistoryCommand.java
  src/main/java/seedu/address/model/HouseholdBook.java
  src/main/java/seedu/address/model/household/Household.java
  src/main/java/seedu/address/model/household/HouseholdContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/household/HouseholdId.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: priority.High

#59 Updated Product Scope in Developer Guide
  docs/DeveloperGuide.md
Labels: type.Enhancement

#70 Update dg
  docs/DeveloperGuide.md
Labels: type.Enhancement

#90 Fix formatting bugs in session
  src/main/java/seedu/address/logic/parser/AddNoteCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteSessionCommandParser.java
  src/main/java/seedu/address/logic/parser/EditSessionCommandParser.java
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: priority.Medium

#183 Fix edit-session bug
  src/main/java/seedu/address/logic/commands/EditSessionCommand.java
  src/test/java/seedu/address/logic/commands/EditSessionCommandTest.java
Labels: alpha-bug
